export const SET_ALERT ='SET_ALERT'
export const REMOVE_ALERT='REMOVE_ALERT'
export const ADD_PAGE ='ADD_PAGE'
export const PAGE_ERROR='PAGE_ERROR'
export const GET_PAGE ='GET_PAGE'
export const CLEAR_PAGE_DATA ='CLEAR_PAGE_DATA'
export const SORT_PAGE ='SORT_PAGE'